### ISSUE TITLE
Assets: use less instead of css

### ISSUE THREAD

**Issue by f3l1x** [pehapkari/pehapkari.cz#113]
## Pros
- easy css management
- DRY
- KISS

## Cons
- dependency (nodejs / composer)

**Comment by TomasVotruba** [comment]
Just wondering, is there some PHP package we might use?

I would try to keep dependencies as minimum as possible.

**Comment by f3l1x** [comment]
Sure. 

https://github.com/leafo/lessphp

**Comment by TomasVotruba** [comment]
Great. If you have an idea how to achieve this, please send PR

**Comment by f3l1x** [comment]
@TomasVotruba Sure. Can you please assigne to me?

**Comment by TomasVotruba** [comment]
@f3l1x You're there! I've added you to the members of the group.

**Comment by TomasVotruba** [comment]
Ping @pavelvondrasek

**Comment by TomasVotruba** [comment]
Until we agree upon single pre-processor this would not bring any value.

Closing for now.
