### ISSUE TITLE
Create page with people who want lecture and mentor

### ISSUE THREAD

**Issue by tomaskazatel** [pehapkari/pehapkari.cz#122]
Separate page with people from community who want lectures and/or mentor other people inside or outside the community.

- [x] Full name
- [x] Contact
- [ ] What want to lecture
- [x] What want mentor
- [x] Social media contact (maybe)

What do you think @TomasVotruba @chemix

**Comment by TomasVotruba** [comment]
I'd start with mentoring, since it quite requested around myself. We can ad lecture page later.

For inspiration, see my old mentoring page: https://github.com/TomasVotruba/tomasvotruba.cz/blob/68ede20fde44a4ef680d952dfc7aadafbd89c13a/source/zkus-si-mentoring.twig

**Comment by TomasVotruba** [comment]
Ping. What's the status for this?

**Comment by TomasVotruba** [comment]
Could we move with this? I think it can be short work.

Maybe we could start with simple page with one mentor.

I'll take care of text and everything, feel free to just add a page.

**Comment by TomasVotruba** [comment]
I'm taking this

**Comment by TomasVotruba** [comment]
Resolved by #151
