### ISSUE TITLE
[place] Jablotron - bad navigation

### ISSUE THREAD

**Issue by integer** [pehapkari/pehapkari.cz#124]
https://pehapkari.cz/vzdelavej-se/misto-jablotron-praha

"červeným metrem C na Vltavskou, pak 6 minut pěšky" => "metrem C na Nádraží Holešovice, pak 6 minut pěšky"

No fixtures found in repo, so I created this issue instead of PR.

**Comment by TomasVotruba** [comment]
Oh, I'm sorry about this.

Thanks for reporting, I've fixed it in database!

> No fixtures found in repo, so I created this issue instead of PR.

Great job for checking the repo first :+1:

**Comment by TomasVotruba** [comment]
![image](https://user-images.githubusercontent.com/924196/59613815-ded49c00-911f-11e9-9d97-4ba67c8776a2.png)
