### ISSUE TITLE
Odkazy na github repozitáře související s celkovým projektem

### ISSUE THREAD

**Issue by SendiMyrkr** [pehapkari/pehapkari.cz#137]
Nemám přesné informace o tom, jaké věci s projektem souvisí, ale bylo by asi dobré mít nějakou stránku kde by byly takové informace. Jednak na to které s projektem souvisí přímo a pak třeba na nějaké zajímavé/přidružené projekty. Vím, že je google, ale třeba repozitář webu jsem našel jenom tak, že vím, že takhle projekty děláte. Někdo nový/neznalý těch přístupů pak nemusí ani přijít na to, že vůbec může nějaký pull request může poslat. Mně to taky napadlo, až když jste mě o něj požádali na twitteru.

**Comment by TomasVotruba** [comment]
Máš nějakou konkrétní představu jak to udělat?

**Comment by TomasVotruba** [comment]
Pořádáme teď soutěž na psaní článků, takže toto by se teď mělo dostat do povědomí.
