### ISSUE TITLE
Odkazy přímo do repozitáře pro jednotlivé stránky na pehapkari.cz

### ISSUE THREAD

**Issue by SendiMyrkr** [pehapkari/pehapkari.cz#138]
Na podnět @TomasVotruba na slacku, zakládám toto issue. Cílem by mělo být vytvořit na každé stránce projektu odkaz přímo na github pro editaci a vytvoření pull requestu

**Comment by TomasVotruba** [comment]
- [ ] pro blogposty
- [ ] pro zbytek
