### ISSUE TITLE
[blog] add post "revisors"

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#144]
- add revised_by: [1, 2] section into articles
- so there is some value in looking sb else's article

**Comment by enumag** [comment]
and to give articles more significance - "it's not just the writer's opinion, others support it as well"

👍

**Comment by TomasVotruba** [comment]
@enumag Good idea!

![reviewed](https://cloud.githubusercontent.com/assets/924196/21702527/3023ac06-d3ac-11e6-92de-3b4fbc421c24.png)
