### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Majkl578** [pehapkari/pehapkari.cz#162]
Just for the sake of having it. 💯

**Comment by TomasVotruba** [comment]
Way to go!

I guess it's not possible :( 
https://help.github.com/articles/securing-your-github-pages-site-with-https/

> HTTPS is not supported for GitHub Pages using custom domains.

**Comment by Majkl578** [comment]
Too bad :/ , how about a CDN? Github.io feels like a _temporary_ solution for long-term run anyway...

**Comment by TomasVotruba** [comment]
How to do that?

**Comment by VaclavPavek** [comment]
https://www.root.cz/clanky/webhosting-s-cloudflare-bezpecna-cdn-zdarma/ nebo přejít na GitLab kde lze mít vlastní certifikát.

**Comment by TomasVotruba** [comment]
@VaclavPavek Thread might be read by English-reading, stick to issue language please. 

If you setup Gitlab the same way this repository is, I would like to see other advantages.

**Comment by TomasVotruba** [comment]
@Majkl578 I'm curious. What is https good for on static website hosted on Github?

**Comment by Majkl578** [comment]
@TomasVotruba Is that question meant for real, in 2017?
E.g.:
- privacy
- no MITM - even that Slack invite could be abused
- HTTP/2

https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
https://https.cio.gov/everything/

(It doesn't matter where the site is hosted.)

**Comment by TomasVotruba** [comment]
@Majkl578 How is current year related to one's knowledge?

How to do this while keeping this open-sources and automated Travis deploy under few mins?

Last and the most important: would you take care of this whole process?

**Comment by TomasVotruba** [comment]
Ping @grogy

Could you write your plan you suggested me today? It sounded really good

**Comment by tomasfejfar** [comment]
* cloudflare works fine with gitlab pages (see https://www.tomasfejfar.cz/)
* it's transparent proxy to whatever is below
* setup took roughly 4 hours - mostly because the DNS was cached, high TTL, etc.

**Comment by Majkl578** [comment]
@TomasVotruba We can talk about it more on Friday meeting.

**Comment by TomasVotruba** [comment]
@tomasfejfar I miss **why** we need it here.

**Comment by tomasfejfar** [comment]
* prevents ad-injecting on free wifi hotspots
* prevents MITM content injecting (facebook like button injection) - mostly also on free wifi hotspots
* protects privacy of visitors - you don't want to be known that you've read "why quit your corporate job?" on your work time in "a company from financial sector" (i.e. you work in a bank and your internet traffic is monitored).
* improved analytics (HTTPS -> HTTPS sends referer, HTTPS->HTTP does not)
* improved SEO - secure sonnection is known to have some weight in SERP

**Comment by Vrtak-CZ** [comment]
cc @spaze

**Comment by spaze** [comment]
I've done some educational talks about why we need *HTTPS Everywhere*, here are the slides (in Czech, though): [HTTPS všude](https://www.michalspacek.cz/prednasky/https-vsude-proc-f5forum), and slightly more technical (and longer) about [HTTPS in general](https://www.michalspacek.cz/prednasky/https-ctvrtkon). 

@TomasVotruba, if you could find few minutes to read them you should find some ideas on why even a simple static site should be on HTTPS nowadays. But it's actually what others (thanks!) have already said :-)

Except maybe @tomasfejfar's SEO point :-) that's bit controversial (a clever move from Google, nonetheless), and also browsers can be configured to [pass referrers even on protocol downgrades](https://www.michalspacek.cz/prednasky/https-ctvrtkon/referrer).

And yeah, too bad GitHub still doesn't support HTTPS for GitHub Pages with custom domains. Hopefully they will soon, they already have tuned their [headers and shit](https://observatory.mozilla.org/analyze.html?host=github.com).

**Comment by TomasVotruba** [comment]
Sorry, I wasn't clear enought. I understand https need. I asked about need of CDN.

**Comment by tomasfejfar** [comment]
CDN is needed because Github Pages do not allow HTTPS directly on custom domain.

**Comment by TomasVotruba** [comment]
I see, so there are 2 possible solutions:

1. add only CDN to allow https 
2. use VPS hosting and deploy via Travis with rsync 

Rights?

**Comment by Majkl578** [comment]
I was only talking about CDN because it's a static content so you wouldn't need a VPS or something. :) But of course it could be just a regular hosting or a VPS.

**Comment by TomasVotruba** [comment]
@Majkl578 I would definitely take solution 1. I just can't believe it is so easy and there is no source about that :D 

Prepare what you need for that from me. I'll be waiting at coffee table ;)

**Comment by spaze** [comment]
@TomasVotruba, ah, sorry, missed that. To be fair, Cloudflare is not just a CDN provider, but also a web application firewall, and SSL/TLS terminating proxy (see [Cloudflare's "SSL" modes of operation](https://www.cloudflare.com/ssl/)). And the reverse proxy is what makes it possible to add HTTPS to any site. But Cloudflare is usually referred to as *the CDN provider*. Yeah, `$confusion++`.

Anyway, thanks for adding HTTPS!

**Comment by TomasVotruba** [comment]
@spaze My bad. What would you recommend to do then?

I can setup Travis deployment to some VPS.
But I need somebody who would set this up on Cloudflare/VPS/wherever needed.

**Comment by TomasVotruba** [comment]
Could sb provide VPS or should I pay minimalistic DigitalOcean account?

**Comment by spaze** [comment]
@TomasVotruba Cloudflare is fine in this case. Also easier (and cheaper I guess) to set up.

**Comment by TomasVotruba** [comment]
@spaze Ok. Let's try it then. 

What do we need? Could you help with that?

**Comment by spaze** [comment]
@TomasVotruba Happily :-)

Here's what's needed:
1. [Sign up](https://www.cloudflare.com/a/sign-up) for a Cloudflare account (in this case the free plan is fine)
2. [Enable two-factor authentication](https://www.cloudflare.com/a/account/my-account) (optional but recommended)
3. [Add a new site](https://www.cloudflare.com/a/add-site), Cloudflare will prefill the new DNS records by scanning current recored
4. Change current name servers from `nsX.digitalocean.com` to Cloudflare-provided name servers, I guess you do that in your domain registrar admin interface
5. The site's will be served via Cloudflare once the browsers will start to query Cloudflare's DNS servers (there's no downtime, the site should be accessible either via CF, or not, the site doesn't really change and the origin servers – Github's in this case – are still up and running, no conf changes)
6. This can be verified in the browser, see `Server` response header, it should say `cloudflare-nginx`
7. According to [the docs](https://support.cloudflare.com/hc/en-us/articles/203045244-How-long-does-it-take-for-CloudFlare-s-SSL-to-activate-), it can take up to 24 hours to "enable" the SSL/TLS certificate
8. *...so just wait*
9. To redirect HTTP to HTTPS you can use Cloudflare's page rules, [this howto](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/#step3timeforssl) should make it clear how
10. Lock down the domain to prevent unauthorized changes (optional but strongly recommended), you can do it with CZ.NIC by [sending a request](https://www.nic.cz/whois/publicrequest/) or using a [tool they provide](https://www.domenovyprohlizec.cz/)

I can help with the Cloudflare part but I'm not exactly sure what account to use for setting it up. I don't think it would be clever to use mine, although *you can trust me™* it might create some issues when the account needs to recovered or settings quickly changed. This is up to you, of course.

**Comment by TomasVotruba** [comment]
@spaze That's very nicely and clearly written :+1: 

I believe you've done more often then I did, so I trust you with this. Taking risk of your death into account (at least we have this manual ;) ).

4. Current name servers are pointed to Github. Let me know the new ones, will change them.

**Comment by spaze** [comment]
Ok, thanks @TomasVotruba :-)

I've now set up Cloudflare to know about pehapkari.cz, can you please change the NS records for the domain as follows? You can either create new NSSET or change the current one (`DIGITALOCEANTV`)

```
ns1.digitalocean.com → amber.ns.cloudflare.com
ns2.digitalocean.com → damon.ns.cloudflare.com
ns3.digitalocean.com → Remove this nameserver
```

(I just wanted this to be documented here, feel free to ping me directly with issues and questions, I'll keep you update here)

**Comment by spaze** [comment]
Lo and behold! **https://pehapkari.cz**

Also redirects are in place:

```
$ curl -I phpkari.cz | grep Location
Location: https://pehapkari.cz/

$ curl -I https://phpkari.cz | grep Location
Location: https://pehapkari.cz/

$ curl -I http://pehapkari.cz | grep Location
Location: https://pehapkari.cz/

$ curl -I http://www.pehapkari.cz | grep Location
Location: http://pehapkari.cz/

$ curl -I https://www.pehapkari.cz | grep Location
Location: https://pehapkari.cz/
```

I can add HSTS and submit both sites to the preload list once we're sure we don't want to go back to plain HTTP. That includes all (future) subdomains, too. There should be no reason for that, though.

**Comment by TomasVotruba** [comment]
Very nice!

Why this is different? :/ 

> $ curl -I http://www.pehapkari.cz | grep Location
> Location: http://pehapkari.cz/

No need for http, feel free to proceed.

**Comment by spaze** [comment]
It would load the page eventually with such rules anyway, especially when HSTS-preloaded, but thanks, I've added the rule now:
```
$ curl -I http://www.pehapkari.cz | grep Location
Location: https://www.pehapkari.cz/
```

Preload list status:
[pehapkari.cz is pending submission to the preload list.](https://hstspreload.org/?domain=pehapkari.cz)
[phpkari.cz is pending submission to the preload list.](https://hstspreload.org/?domain=phpkari.cz)

**Comment by spaze** [comment]
@Majkl578 @TomasVotruba I think we can close this issue as `FIXED`

![My job here is done](https://biochemistry3rst.files.wordpress.com/2014/03/my-job-here-is-done.jpg)

**Comment by TomasVotruba** [comment]
Post in progress: https://github.com/pehapkari/pehapkari.cz/pull/208 :)

**Comment by Majkl578** [comment]
Cool. :+1:
Closing here as it's been resolved.
