### ISSUE TITLE
Display post visits via Google Analytics?

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#165]
https://www.google.cz/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=google+analytics+page+views+by+url&tbs=qdr:y

- https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-php
- https://github.com/google/google-api-php-client

**Comment by TomasVotruba** [comment]
@jakubkratina Ti Tome posílal nějakej skript, tak se na něj mrkni

**Comment by jakubkratina** [comment]
@TomasVotruba co? :D

**Comment by TomasVotruba** [comment]
@jakubkratina To byla poznámka pro mě :D

**Comment by jakubkratina** [comment]
@TomasVotruba Tak proč označuješ mě? :D 🗡

**Comment by TomasVotruba** [comment]
@jakubkratina Jsem byl na mobilu a potřeboval jsem si to nutně připomenout. Kdybych věděl, že na mě vytáhneš svůj :dagger: , vzal bych si :crossed_swords:

**Comment by jakubkratina** [comment]
@TomasVotruba: 🔫

**Comment by TomasVotruba** [comment]
@jakubkratina  :dragon:

**Comment by TomasVotruba** [comment]
After a gap year, obviously not a priotity :)
