### ISSUE TITLE
školení page

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#169]
Přidat nebo pokecat s:

## Oslovit

- [ ] @Vrtak-CZ 

## Osloveno

- [x] @grogy - Git
- [x] @tomasfejfar - ?
- [x] @ondrejmirtes  - ?

## Pošle nástřel

- [ ] @kocourekio Úvod do Nette
- [ ] @OndraM - 22. 7., Fuknční testování

## 2DO

- [x] najít školící místnost
- [x] vytvořit stránku 
- [x] sehnat 3-4 témata
- [x] spustit první školení a zjistit poptávku

### My bychom se postarali o

- zajištění prostor (zaplacení prostor je z ceny za školení)
- propagaci, reklamu, marketing, copy
- vypisování nových termínů podle vašich možností a potřeb

Na to a další růst zvažuju provizi nějakých 30-10 %, postupně klesající, ať je podporováno dlouhodobé školení a odfiltrují se lidi, co jen potřebují reklamní kanály.

### Školitelé by

- školili
- dostávali peníze
- nám dávali zpětnou vazbu, jak to celé udělat lepší
- ?

---

Kdo chcete školit a s kým jsem se už domluvil, napište sem návrhy na školení, viz níže:

--- 

Příklad s rozsahem:

## Ukázkové školení

Anotace, která popisuje, proč mám na školení právě já přijít. Jaký typ člověka bych měl být na začátku, co co mám umět a co je můj problém. Na konci bude vědět a rozumět věcem, které ti předtím přišly nemožné. Ještě bys měl vědět, že znalosti, které probíráme najdeš na Githubu, takže 

- to tě naučím
- tohle taky
- tohle taky
- tohle taky
- i tohle

Odhad trvání: 3 hodiny (nejlíp se vejít do rozsahu 3-8 hodin)

Přibližná cena: 2000 Kč

**Comment by TomasVotruba** [comment]
## Tomáš Votruba - Jak školit efektivně a lidsky  

- TBA

**Comment by tomasfejfar** [comment]
## Tomáš Fejfar - Úvod do PHP

* v rozsahu jako byly Czechitas
    * umím HTML/CSS
    * chci se naučit, jak fungují dynamické stránky v PHP
    * bez frameworku - základní věci
        * podmínky
        * cykly
        * require
        * rozdělování kódu
        * objekty a třídy, pokud bude čas

**Odhad trvání:** 8h
**Cena:** 10.000,- / počet lidí + provize za organizaci pro Péhápkaře + 2000,-/den pro další kouče při větším počtu lidi

**Comment by tomasfejfar** [comment]
## Tomáš Fejfar - PhpStorm

* základy nastavení projektu
* efektivní ovládání
* navigace v kódu
* refaktoring

**Odhad trvání:** 2-3h
**Cena:** 1000Kč/os

**Comment by grogy** [comment]
# Václav Makeš - Úvod do Gitu

**Cílová skupina:** vývojáři bez znalosti verzování

První **nástřel osnovy** níže. (mé původní ucelené školení je koncipováno na 9-10 hodin v kuse, dle [průzkumu](https://pehapkari.cz/blog/2017/01/10/5-temat-po-kterych-php-programatori-touzi/) jsem jej tady upravil):
- motivace proč se ho učit
- uca-cases jenž Git efektivně řeší
- pár slov k historii (opravdu pár, jen tak aby člověk věděl co používá a proč je to dobré, na jakých principech Git stojí)
- první krkoky s verzováním - vlastní repo, první commity
- vypublikování repositáře na privátní / veřejný server
- sledování změn v repositáři

**Odhad trvání:** 3 hodiny
**Přibližná cena:** 1000 Kč

-----

*Toto je opravdu nástřel, před veřejným vypublikováním si připravím slides a celé to vyzkouším, abych se časově vešel.*

**Comment by grogy** [comment]
# Václav Makeš - Mírně pokročilé pokračování Gitu

**Cílová skupina:** vývojáři se základní znalostí Gitu

První **nástřel osnovy** níže. (mé původní ucelené školení je koncipováno na 9-10 hodin v kuse, dle [průzkumu](https://pehapkari.cz/blog/2017/01/10/5-temat-po-kterych-php-programatori-touzi/) jsem jej tady upravil):

- vnitřnosti Gitu, aneb Git je easy
- interaktivní rebase
- větvení
- workflow a jejich typické use-cases
- efektivní práce s Gitem
- konvence při práci s Gitem
- ukázka co znalost verzování umožní (CI, CD, CR, etc.)

**Odhad trvání:** 3 hodiny
**Přibližná cena:** 1000 Kč

----

*Toto je opravdu nástřel, před veřejným vypublikováním si připravím slides a celé to vyzkouším, abych se časově vešel.*

**Comment by ondrejmirtes** [comment]
Ondřej Mirtes - rapidní vývoj, continuous delivery
===================

* "Zkracování feedback loop" ([úvod do problematiky](https://ondrej.mirtes.cz/zkracovani-feedback-loop))
  * jak tvořit zadání se zadavatelem tak, aby vývoj proběhl hladce a zadavatel obdržel to, co chce
  * jak zorganizovat práci v týmu a programovat tak, aby nedocházelo ke všemožným problémům, bugy na produkci, nefunkční aplikace
* Continuous Integration - vytvoření build skriptu, rozběhání CI serveru, doporučení k problematice
* Přerod zastaralé aplikace v novou bez kompletního přepisu - stranger pattern, jak na refaktoring
* Bezvýpadkové databázové migrace, bezvýpadkové a časté nasazování

**Comment by ondrejmirtes** [comment]
Ondřej Mirtes - testování
==================

* Zavádění testů a testovací kultury - jak naučit a přesvědčit vývojáře, aby testy psát chtěli, jak přesvědčit management, že testy potřebuje
* Psaní testovatelného kódu, související návrhové vzory
* Základní a pokročilé funkce PHPUnitu, code coverage
* Upgrady na novější verze PHP (7.0, 7.1) a z toho plynoucí výhody a dopady na kód

**Comment by ondrejmirtes** [comment]
Ondřej Mirtes - asynchronní PHP
==========

* Jak toho udělat více s menšími nároky na servery
* Princip fungování, přirovnání k Node.js
* Promises do hloubky, příklady využití (např. [Jak se pomocí nich zbavit větví v kódu](https://ondrej.mirtes.cz/zbavte-se-vetvi-v-kodu-pomoci-promises))
* Využití při zpracování message queues, RabbitMQ
* Využití při realtime komunikaci pomocí WebSockets
* Asynchronní HTTP requesty, SQL dotazy, přístup na filesystem
* Přehled nejlepších open-source balíčků a zdrojů

Odhad trvání: 4 hodiny
Přibližná cena: 1 999 Kč / účastník

**Comment by TomasVotruba** [comment]
@martinahynkova Here

**Comment by TomasVotruba** [comment]
@kocourekio Štěpáne, můžeš prosím své školení hodit sem?

**Comment by kocourekio** [comment]
# Štěpán Kocourek - Úvod do Nette

- adresářová struktura (+ best practices)
- Dependency Injection a běhové prostředí, konfigurace
- Tracy Debugger a eliminace chyb
- Model-View-Controller: presenter a životní cyklus
- Latte: silný šablonovací jazyk a dědění šablon
- databáze: nativní podpora ve frameworku
- routování: vytváření odkazů a hezkých URL v jakékoliv podobě
- úvod do formulářů

**Odhad trvání:** 4-5 hodin
**Přibližná cena:** 2 499 Kč / účastník

**Comment by TomasVotruba** [comment]
@kocourekio Ahoj Štěpáne, jdu na to. Nezapomněl jsem, jen jsem minulý týden řešil první Ondrovo školení.

Vypadá to ok, možná bych změnil pořadí, ať je na úvod jasné, co je MVC a jak Nette pracuje a  související části jsou u sebe:

- adresářová struktura (+ best practices)
- routování: vytváření odkazů a hezkých URL v jakékoliv podobě
- Model-View-Controller: presenter a životní cyklus
- Dependency Injection a běhové prostředí, konfigurace
- Tracy Debugger a eliminace chyb
- Latte: silný šablonovací jazyk a dědění šablon
- databáze: nativní podpora ve frameworku
- úvod do formulářů

Zvládneš to za 4 hodiny? Cena super.

**Comment by kocourekio** [comment]
@TomasVotruba Určitě, jsem pro. ;)

**Comment by TomasVotruba** [comment]
Díky za bleskovou odpověď :)

Pošli teda pull-request na info se školeníma prosím: https://github.com/pehapkari/pehapkari.cz/blob/90054bd569b01f0461748d210d39d85e0cadb58f/source/_data/trainings.neon#L35-L51

Ještě to učešem

**Comment by kocourekio** [comment]
@TomasVotruba Až budu u PC, předpokládám večer. :)

**Comment by kocourekio** [comment]
@TomasVotruba Omlouvám se za zpoždění. https://github.com/pehapkari/pehapkari.cz/pull/296

**Comment by TomasVotruba** [comment]
Issue zavírám, protože hlavní body jsou vyřízeny.
Pro nové školení otevři nové issue
