### ISSUE TITLE
[trainings] Show message when training planned but past deadline

### ISSUE THREAD

**Issue by tomasfejfar** [pehapkari/pehapkari.cz#190]
**Why?** 

When training is planned, but it's past deadline it's not obvious what's happening if anyone gets there from Google or otherwise without context. It just seems that someone forgot to include the sign up button. 

There is the date displayed in the sidebar, there is "add to calendar" but there is no "sign up for this training" nor "signups for this training are closed". 

**Resolution:**

Add "Přihlášky na tento termín byly již uzavřeny" when training is past deadline and keep it until the date is completely removed (no next training planned) or replaced by new date. 

![image](https://user-images.githubusercontent.com/642928/65435799-5f8eec80-de21-11e9-9336-3dcc790eb16a.png)

**Comment by TomasVotruba** [comment]
PR?

**Comment by tomasfejfar** [comment]
When I know it's not intentional (not sure how it could be, but still). I vaguely remember there was some message like that there, but it disappeared.

**Comment by TomasVotruba** [comment]
Go for it

**Comment by TomasVotruba** [comment]
Free free to send PR. Closing as part of cleanup
