### ISSUE TITLE
Make Statie less annoying

### ISSUE THREAD

**Issue by mrtnzlml** [pehapkari/pehapkari.cz#194]
This is probably Statie issue, but it's closely related to this project. Statie doesn't regenerate ouput after save (very often) and sometimes it simply dies with:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                
Type error: file_get_contents() expects parameter 1 to be a valid path, boolean given 
```

It's super annoying to restart server every time a want to see changes.

**Comment by TomasVotruba** [comment]
Ref: https://github.com/Symplify/Symplify/issues/30

**Comment by TomasVotruba** [comment]
Ref: https://github.com/Symplify/Symplify/issues/35
