### ISSUE TITLE
Docker probably broken

### ISSUE THREAD

**Issue by enumag** [pehapkari/pehapkari.cz#198]
I'm not using docker so I can't test it at the moment but I assume that [this](https://github.com/pehapkari/pehapkari.cz/blob/master/.docker/Dockerfile#L17) won't work correctly, right? Not sure if it's enough to change sculpin to statie.

**Comment by TomasVotruba** [comment]
This should do:

- https://github.com/pehapkari/pehapkari.cz/commit/cd65fe7ce822af0b9da5e71666090c18e47a8ba8
- https://github.com/pehapkari/pehapkari.cz/commit/93c3d13b5ba6e489fca4e995d4bd6ad7730df577

Do you mean anything else?

**Comment by enumag** [comment]
Should be ok.

**Comment by TomasVotruba** [comment]
Thank for reporting
