### ISSUE TITLE
Instead of 404, 500 error is returned

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#207]
Etc: https://pehapkari.cz/asdf

Error is `Return value of Pehapkari\Github\Collector\ResolvedTemplateNameCollector::getTemplateName() must be of the type string, null returned`

**Comment by TomasVotruba** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/924196/71308320-3a4b5380-23fb-11ea-9471-5482cbdb796e.png)
