### ISSUE TITLE
O jaké školení máte zájem

### ISSUE THREAD

**Issue by VaclavPavek** [pehapkari/pehapkari.cz#223]
O jaká školení by jsi měl zájem a nenašel jsi je v issues https://github.com/pehapkari/pehapkari.cz/issues/169

**Comment by VaclavPavek** [comment]
# Docker

- výhody / nevýhody
- tvorba vlastního obrazu / úprava existujícího (pokud mám .dockerfile)
- tagování
- předávání proměnných do kontejneru

## Ukázkový kontejner

- Apache + PHP + vlastní konfigurační soubor pro Apache a PHP
- tipy pro ladění na produkci

**Comment by wodCZ** [comment]
# Refaktoring, práce s legacy projektem
Zajímaly by mě techniky, které by mohly pomoct s přebíráním legacy projeků. Jak postupovat s vytvářením testů takovýhle projektů, jak kód bezpečně zrefaktorovat a podobně. Zkrátka jak dělat s legacy kódem a nepo**at se z toho. Možná @mrtnzlml by k tomu uměl něco říct? Nevím, Martine, jak moc se do této komunity a jejích aktivity angažuješ, tak se kdyžtak prosím nezlob za mention.

**Comment by mrtnzlml** [comment]
Ahoj @wodCZ. Základem úspěchu jsou dva jednoduché kroky:

1) zjisti proč to došlo až do tohoto stavu a
2) zařiď odchod těchto lidí z firmy, protože pokud je ten projekt v takovém kreku jako jsem se setkal já, tak ti lidé nejsou *dlouhodobě* dostatečně kompetentní a nezlepší se to - jsou to prostě špatní programátoři a jejich špatní vedoucí

Z mojí strany o to asi nemám zájem, protože bych nedokázal podat dostatečně objektivní svědectví. Navíc většina lidí si pod pojmem "legacy" představuje něco malinko jiného. Když jim pak popíšu to "true legacy" se kterým jsem se setkal já, tak většinou prohlásí něco ve smyslu **oh fuck** a společně se akorát zasmějeme... :)

Rád tento úkol tedy přenechám někomu, kdo se setkal s reálným legacy co trápí každého a ne s hroudou proděravělého bláta žijícím v globálním prostoru, co nemá žádnou hodnotu.

**Comment by TomasVotruba** [comment]
@jakubkratina Je tu zájem o školení Dockeru :+1: 
Co ty na to?

**Comment by jakubkratina** [comment]
@TomasVotruba o Dockeru nevím tolik, abych ho školil. Ale zeptám se Daniela (na slacku veeenex), jestli by měl zájem.

**Comment by VaclavPavek** [comment]
@jakubkratina mě docela pomohlo tvé video na twitchy. Docker bych měl spíše na hraní místo VirtualBoxu (platilo v době kdy jsem psal issue), ale uvědomil jsem si, že VirtualBox je pro mě v současné době stále nejlepší řešení - lze snadno přesunout na pc s Windows v případě havárie NTB (já mám Linux). Zajímavé by bylo vytvoření vývojového prostředí pro Nette / Symfony ala Laravel/Homestead.

**Comment by jakubkratina** [comment]
@VaclavPavek To rád slyším, že ti to pomohlo :) Jak to myslíš s tím přesunem? U dockeru je to právě ještě jednodušší - `docker pull <image>` && `docker run ..` a máš všechno.

**Comment by VaclavPavek** [comment]
@jakubkratina když by mi odešel NTB tak mám celé vývojové prostředí v jednom diskovým image bez nutnosti cokoli nastavovat a řešit na NTB s Windows (sebral bych manželce NTB). Windowsy jsem už hóóóódně dlouho nepoužíval a ani to nemám v plánu.

**Comment by jakubkratina** [comment]
@VaclavPavek Nevím co vše myslíš vývojovým prostředím, ale v docker image právě máš kompletní nastavení, os, software (git, npm atp.) a neřešíš platfotmu a nic nenastavuješ. Jen nainstaluješ docker a spustíš container. Ale pokud mluvíš třeba o IDE atp. tak o to se ti docker samozřejmě nepostará :)

**Comment by VaclavPavek** [comment]
@jakubkratina když jsem naposledy zkoušel docker na Winrodws tak to nějak nefungovalo. Ve VirtualBoxu mi stačí vytvořit vpc a připojit diskový image. V každém případě díky za tvé video.

**Comment by VeeeneX** [comment]
@jakubkratina Veľmi dobrý nápad nemám s tým problém. Ešte by sme mohli osloviť chalanov z #Docker. Nám sa vtedy podarilo usporiadať aj Docker Birthday party. 

@vaclavpavel Napríklad ja mam v dockery celé prostredie, vývoj, testing aj staging. A výhoda? Na svojej masine nemám nič. Len samé image, stačí mi clean install s dockerom :D

Ohľadom nejakého školenia môžem ukázať ako vytvoriť prostredie pre Laravel :)

**Comment by Lexinek** [comment]
Mě by dost zajímalo https://github.com/pehapkari/pehapkari.cz/issues/169#issuecomment-273931044 od @ondrejmirtes je to nějak v budoucnu v plánu?

**Comment by TomasVotruba** [comment]
Školitelů je už je dost, teď na samotná školení :)
