### ISSUE TITLE
název písma v logu

### ISSUE THREAD

**Issue by xpavp03** [pehapkari/pehapkari.cz#226]
Kdo víte, můžete prosím doplnit název fontu do http://pehapkari.cz/press/ ?
Jestli se dá někde stáhnout zdarma, tak včetně odkazu.

Díky

**Comment by TomasVotruba** [comment]
Ping @bretislavstepan

**Comment by bretislavstepan** [comment]
Font: Diavlo
Řez: Bold
Download: http://www.exljbris.com/diavlo.html

**Comment by xpavp03** [comment]
Díky, založil jsem #228.

**Comment by bretislavstepan** [comment]
Mám zkusit připravit PR stránky?

**Comment by TomasVotruba** [comment]
Perfecto!
