### ISSUE TITLE
[post] aktualizace knihoven

### ISSUE THREAD

**Issue by grogy** [pehapkari/pehapkari.cz#226]
Dává vám smysl kratší článek o aktualizaci závislostí v PHP? Má představa je zaměřením spíše pro začátečníky. Popsat co, proč, jak. Jaké to má dopady a co se k aktualizaci může hodit.

**Comment by TomasVotruba** [comment]
Máš někde draft, abych juknul?

**Comment by grogy** [comment]
Ani bych neřekl, že to je draft - https://pehapkari.slack.com/archives/C4594KCUA/p1572954236010800?thread_ts=1572947787.009800&cid=C4594KCUA

Co bych například chtěl dát navíc:
- info k deploy
- info k Rector toolu
- ekonomické dopady
- rozdíl pro knihovny vs. frameworky

**Comment by TomasVotruba** [comment]
Na Slaku nejsem. Screen/me gist?

**Comment by grogy** [comment]
Jasně, citace sám sesbe ze Slacku:

> nejlepší je dělat upgrade pravidelně. Pokud to nejde (často) tak postupuji následovně:
>
> 1/ spouštím upgrade postupně na jednotlivé balíčky [1] s parametrem --with-dependencies
> 2/ pokud existuje upgrade file jako např. [3] tak jedu podle něj
> 3/ kontroluji v changelu co se změnilo např. na Githubu to vypadá příjemně a dobře se hledá [2]  - pokud neexistuje, tak v repositáři hledám soubory typu changelog
> 4/ po upgrade knihovny / skupiny knihoven otestuji aplikaci (automatizovaně co je pokryto, zbytek proklikám já nebo dedikovaný tester podle projektu)
>
> [1] https://getcomposer.org/doc/03-cli.md#update-u
> [2] https://github.com/nette/tester/releases
> [3] https://github.com/doctrine/dbal/blob/master/UPGRADE.md

**Comment by TomasVotruba** [comment]
Díky. Dobrá náhoda, zrovna jsem psal o něčem podobném, aktualizaci PHPUnit 4 na 8.
Zajímal by mě tvůj pohled na tenhle nadpis https://www.tomasvotruba.cz/blog/2019/11/04/still-on-phpunit-4-come-to-phpunit-8-together-in-a-day/#2-single-version-upgrade-1-pull-request

Uměl bys to představit na reálném kódu s reálnými čísly, např. tolik řádku, Nette použito (use Nette..., Nette::call() atd.) na x. místech, tenhle PHP kód mě zasekal šlo?

To by bylo pro lidi prakticky aplikovatelné. 

Jinak téma super, hlavně teď kolem velkých releasů PHP, Symfony a PHPUnitu. Pojďme do toho

**Comment by grogy** [comment]
Jasně, dokážu to včetně časové náročnosti. Čeká mě tu jeden projekt z Symfony 3.4 na last, takže čísla si k tomu získám. Starší Nette projekt, který bych mohl publikovat asi nemám.

Bude to trošku větší než jsem čekal, ale proč ne - aspoň to bude mít větší efekt. :)

Tento týden udělá draft. Ten Ti pošlu. Pak budu řešit upgrade a podle toho doplním konkrétní data

**Comment by TomasVotruba** [comment]
> Symfony 3.4 na last

Zajímalo by mě, jak si s tím poradí Rector. Tyhle sety máme na 90 % pokryté. Config + šablony budeš muset ručně = prostor pro rozepsání v článku.

> Bude to trošku větší než jsem čekal, ale proč ne - aspoň to bude mít větší efekt. :)

Klidně to rozděl na 2 články.  Třeba ta Doctrine vypadá na samostatný blok :)

Btw, English nebo česky? Anglicky to bude mít hnedka 10x násobný reach a budu to moc sdílet na konferencích jako řešení :)

**Comment by grogy** [comment]
Rector na toto každopádně vyzkouším. Bude to součástí kolik toho udělal sám tool + kolik pravidel jsem případně musel dopsat nebo vyřešit ručně.

Rozdělení na 2 články možná udělám. Doctrine mám všude v posledních verzích, ale najdu i jiné knihovny.

Dosah anglicky psaného článku chápu, ovšem nejsem si jist, že bych to nyní zvládnul. Pro začátek to budu psát česky a pokud to bude dobré, tak bych řešil překlad ;-)

**Comment by TomasVotruba** [comment]
Sounds like a plan :+1: Těším se :)

**Comment by TomasVotruba** [comment]
Any update? 

Uzavírám issues a dotahuju problémy. Kdyžtak bych to zatím zavřel, bo je to odpvězené a next step jsou na tobě. Jsi s tím ok?

**Comment by grogy** [comment]
Ahoj Tomáši,

díky za pingnutí. Musel jsem dát prioritu jiným věcem, ale s tímto počítám. Důležitý je pro mě feedback, že napsat něco takového dává pro komunitu smysl. Jak to bude aktuální, tak se opět ozvu. Díky moc
