### ISSUE TITLE
404 not working

### ISSUE THREAD

**Issue by Majkl578** [pehapkari/pehapkari.cz#241]
404 returns GitHub error page instead of our custom error. :/
https://pehapkari.cz/blahblah

**Comment by TomasVotruba** [comment]
Got any suggestion?

**Comment by Majkl578** [comment]
GitHub expects file 404.html in the root of gh-pages repo.
Statie generates 404/index.html. No idea how to fix/hack/change that to generate different filename...

**Comment by TomasVotruba** [comment]
I see. Thank you.

@ikvasnica Got any ideas? How did you solved this?

**Comment by ikvasnica** [comment]
@TomasVotruba I did not, unfortunately. As Majkl578 pointed out, it generates the output into its own directory.

**Comment by Majkl578** [comment]
@TomasVotruba I consider this an issue due to Statie behavior. How easy/hard would it be to change Statie to let user override the output file path/format, i.e. in the Neon metadata?

**Comment by TomasVotruba** [comment]
Moved to https://github.com/Symplify/Symplify/issues/253
