### ISSUE TITLE
Language / Jazyk

### ISSUE THREAD

**Issue by rapemer** [pehapkari/pehapkari.cz#242]
Ahoj,

jsem sám tak trochu vyděšen z toho, že půlka článků je psána česky a půlka anglicky? A že není žádný přepínač, který by indikoval jazykovou mutaci?

1. Je-li cílová skupina komunity zaměřená na Českou Republiku (soudě dle názvu asi ano), nedává smysl psát v angličtině.

2. Je-li cílová skupina mezinárodní, pak by bylo vhodné zrušit český název a psát pouze anglicky.

3. Je-li cílová skupina ČR a zároveň si autor chce procvičit AJ, bylo by vhodné vytvořit překlady daných článků, aby si každý vývojář mohl vybrat, co je mu příjemnější ;-) S tím souvisí možnost filtrovat články dle jazyka ...

**Comment by Majkl578** [comment]
Pokud vím, cíl je expandovat/rozšířit audienci i o EN, jen se to ještě nezrealizovalo. A upřímně, zrovna u _vývojářů_, kteří denodenně čtou EN manuály apod., bych nečekal, že jim bude angličtina nepříjemná.
Víc k věci vysvětlí spíš @TomasVotruba.

**Comment by TomasVotruba** [comment]
Ahoj, logika je jednoduchá: **cílová skupina a tedy jazyk je podle tématu článku**. Pokud píšu o Nette srazu, píšu spíš česky, pokud píšu o Laravelu, píšu anglicky.

Tedy podoba verze 3. Z tvého textu jsem vyčetl 2 feature requesty:

- bylo by vhodné vytvořit překlady daných článků, aby si každý vývojář mohl vybrat, co je mu příjemnější - s tím souvisí možnost filtrovat články dle jazyka ...

Co z toho potřebuješ natolik, že bys byl ochotný si to vzít na starost?

**Comment by TomasVotruba** [comment]
Ping

**Comment by Matthw98** [comment]
S překlady daných článků vám můžou pomoci na [www.prekladysro.cz/anglictina](url). Můžu jedině doporučit co se týče poměru cena/výkon ;)

**Comment by TomasVotruba** [comment]
@Matthw98 Vypadá to, že to není tak důležité. Navíc jsme komunita, tak jedeme na dobrovolné motivaci.

**Comment by rapemer** [comment]
@TomasVotruba Ahoj Tome, neřeším problém, jen se zamýšlím nad tématem multijazyčnosti ;-) Samozřejmě si rád přečtu jak české, tak anglické články. Nicméně by bylo zajímavé psát články v angličtině, zpětně je překládat do ČJ a nechat návštěvníka vybrat, co je mu příjemnější.

Co se týče ochoty, ta je, nicméně nejsem dvakrát velký příznivec Nette a nejsem si jist, zda bych byl pro takovou funkčnost správný vývojář :-)

PS: sorry za časovou prodlevu, měl jsem toho moc

**Comment by TomasVotruba** [comment]
@rapemer Pohodka. Díky i za tuhle reakci. Mám potřebu to vysvětlit z hlediska životního cyklu komunitního open-source projektu.

Chápu, že je to zajímavé. Stejně jako by bylo zajímavé, kdyby někdo psal jeden článek týdně ve dvou různých jazycích, k oběma testy, poslal by je do 3x PHP newsletterů, Tweetnul to, hodil link FB... 
Tím nechci schazovat tvou názor!

Nicméně v rámci open-source je potřeba, aby za "zajímavost" **dosáhla hranice "chci investovat energii a udělat změnu, protože je to pro mě důležité"**. Jinak by tu už ležely stovky "nice-to-have" issues.

Kdybys do toho někdy chtěl jít (klidně i strojový překlad s Google Translator), rád tě navedu a pomůžu ti :handshake:
