### ISSUE TITLE
Local Windows installation bug

### ISSUE THREAD

**Issue by ubkpesek** [pehapkari/pehapkari.cz#250]
I've tried different scenarios but I am still not able to make it run. I am running it on Windows 10.

1. using PHP built in server

when running `php bin/console doctrine:schema:create` I am getting :
```
In MappingException.php line 22:
 The class 'Pehapkari\Marketing\Entity\MarketingEvent' was not found in the chain configured namespaces Vich\UploaderBundle\Entity, AlterPHP\EasyAdminExtensionBundle\Model
```
I also tried to skip this step to see what will be the result but I got:
`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "videos" as such route does not exist."). in \templates/_snippets/menu.twig (line 20) `

2. using Docker (I am not a Docker guy)

![image](https://user-images.githubusercontent.com/49426615/69541359-3ad20500-0f89-11ea-8fcd-8fc8da4409b4.png)

And then it gets stuck (docker-compose ps)
`pehapkaricz_web_1       docker-php-entrypoint apac ...   Restarting`

**Comment by KamilPesek** [comment]
Anyone? I would say problem is with files defined in packages not in src.
![image](https://user-images.githubusercontent.com/25612952/69903165-73f9e300-1396-11ea-8412-ecdc3925bef8.png)
![image](https://user-images.githubusercontent.com/25612952/69903170-7c521e00-1396-11ea-999c-05ecb47e9500.png)
It wrongly checks/serches only in "packages/Training" directory.

**Comment by ubkpesek** [comment]
I just wanted to fix at least two bugs which I discovered ...

**Comment by JanMikes** [comment]
Hi, i am sorry for such late reply.

Let me look into this, i am able to test it with docker and if any bug found then fix it.

**Comment by JanMikes** [comment]
This is weird, i was able to run `docker-compose up --build` without any issues locally :-/

**Comment by JanMikes** [comment]
Btw do not run `php bin/console doctrine:schema:create` you should run instead `php bin/console doctrine:migrations:migrate`

I am still investigating what is wrong.

**Comment by JanMikes** [comment]
Sorry, i personally am giving up, could not replicate it in less than hour.

**Comment by TomasVotruba** [comment]
Closing as Windows related and Windows guru is needed.
