### ISSUE TITLE
Jak snadné je používat CI: nefunkční odkaz na výsledek

### ISSUE THREAD

**Issue by Majkl578** [pehapkari/pehapkari.cz#255]
https://github.com/pehapkari/pehapkari.cz/blob/805a37a0244191233c2f663c4b944e5f04d0997f/source/_posts/2017/2017-03-08-jak-snadne-je-pouzivat-ci.md#hotov%C3%BD-k%C3%B3d-ke-sta%C5%BEen%C3%AD

Nefunkční odkaz na GitLab (vyžaduje přihlášení), viz komentář pod článkem. Můžeš se na to podívat, @hranicka? Díky.

**Comment by hranicka** [comment]
Fixed. Sorry.

**Comment by Majkl578** [comment]
👍 Díky.
