### ISSUE TITLE
Make a sniff to filter out trailing whitespaces

### ISSUE THREAD

**Issue by Majkl578** [pehapkari/pehapkari.cz#256]
See https://github.com/pehapkari/pehapkari.cz/pull/253#issuecomment-287766861.

**Comment by TomasVotruba** [comment]
It looks like there is new fixer in PHP-CS-Fixer 2.2, that should do this: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2603/files

Can you confirm it does the job?

**Comment by TomasVotruba** [comment]
Ping
