### ISSUE TITLE
Tested Articles: Automatic checks of tests

### ISSUE THREAD

**Issue by jkuchar** [pehapkari/pehapkari.cz#287]
When I was writing #285 and then #286 I got quite angry because I was not able to get my code pass thru code style checker. It took me more time than writing actual tests for the article. This is not the way to go.

## Formatting
- Is that crucial how tests for articles are formatted? Maybe just recommend PSR-1? Isn't that enough?

## Code quality
- code checker is checking things that are worth measuring in a big long-term project (not in an article) (method complexity, max methods, ...)
- Shouldn't be that up to the author what he wants to check in his code?
   - When does someone want to write an article about coding standard? He must break pehapkari coding standard by definition.
   - Or demonstrate bug which PHPStan finds and breaks build. It was an intentional demonstration. Responsibility should be up to the author to decide how his article should be tested and if he wants static analysis at all.

## Portability
- it cares about details like wich line-ending do I use (CRLF on Windows)
- checker and fixer [does not work](https://github.com/jkuchar/pehapkari.cz/commit/379b11983ca399f75ae23a6c7716d082d96d8a8a#diff-8091e3a339db06fa8db3392a2ea72d7eR22) on Windows

**Comment by TomasVotruba** [comment]
I will fix issues first, so we know narrow scope to relevant parts.

What checker reports `CRLF`? We can remove that.

**Comment by jkuchar** [comment]
It is quite strange, it does not show message what is wrong and line...

![image](https://cloud.githubusercontent.com/assets/133822/26530119/b8871bcc-43ce-11e7-85a4-df9cd60fe161.png)

But it look like that these two are making problems:
PhpCsFixer\Fixer\Whitespace\LineEndingFixer
PhpCsFixer\Fixer\NamespaceNotation\BlankLineAfterNamespaceFixer

When I run `vendor\bin\easy-coding-standard check src tests > output.txt` I get [output.txt](https://github.com/pehapkari/pehapkari.cz/files/1034294/output.txt). 

![image](https://cloud.githubusercontent.com/assets/133822/26530146/630e360c-43cf-11e7-95a7-1b967d0c7403.png)

**Comment by TomasVotruba** [comment]
@jkuchar Perferct report, thank you. I will get to that till the end of next week.

**Comment by TomasVotruba** [comment]
Since May 2017 there have been many improvements in EasyCodingStandard. Even fixes for screens you added.

As related PR with tests is merged: https://github.com/pehapkari/pehapkari.cz/pull/300, I'm closing this.

If you find any issue in your next tests, report it at [Symplify issues](https://github.com/Symplify/Symplify/issues) please, thank.
