### ISSUE TITLE
[blog] jednoslabičné předložky

### ISSUE THREAD

**Issue by jkuchar** [pehapkari/pehapkari.cz#294]
![image](https://user-images.githubusercontent.com/133822/27002677-d97ec758-4de7-11e7-8d26-7a8650161c1b.png)

Všiml jsem si, že na rozdíl od Texy! formátovače, Markdown formátuje český text proti pravidlům českého pravopisu. Je možné s tím něco udělat? Mělo by stačit výstup prohnat tímto: [Texy typografický modul](https://github.com/dg/texy/blob/master/src/Texy/Modules/TypographyModule.php)

**Comment by TomasVotruba** [comment]
Klasické `&nbsp;` nestačí? Tak to většinou řeším.

**Comment by jkuchar** [comment]
Jo, ale stejný problém má i obsah článků,

**Comment by TomasVotruba** [comment]
Rozumím.

Toto je záležitost Statie, která renderuje obsah článku do Latte/Markdownu. 

Mělo by stačit přidat formátovač sem: https://github.com/Symplify/Symplify/blob/fc0ab5eb9a47dc05fc98f8f2ed6b6c9834914718/packages/Statie/src/Renderable/RenderableFilesProcessor.php#L85

Pošleš PR?

**Comment by TomasVotruba** [comment]
Je to tady dlouho bez reakce, tak zavírám.

Možnost s PR stále platí
