### ISSUE TITLE
Update HTTPS post to use new Always use HTTPS button

### ISSUE THREAD

**Issue by spaze** [pehapkari/pehapkari.cz#297]
Cloudflare made it easier to redirect HTTP to HTTPS by [adding a new button](https://blog.cloudflare.com/how-to-make-your-site-https-only/). Change [the post](https://pehapkari.cz/blog/2017/03/13/how-to-add-https-to-github-pages-in-6-steps/) to reflect that.

The post was added in #208.

**Comment by TomasVotruba** [comment]
Could you take care of that or  do you need any help?

**Comment by spaze** [comment]
Created #309 to address this.

**Comment by TomasVotruba** [comment]
Thanks"
