### ISSUE TITLE
Error on article blog

### ISSUE THREAD

**Issue by lukasojd** [pehapkari/pehapkari.cz#302]
Hi, 

I found error on site pehapeckari.cz. On page is error 500. Can you site fix? 

Example: https://pehapkari.cz/blog/2017/03/20/jak-posilat-e-maily-pres-amazon-ses/

**Comment by TomasVotruba** [comment]
Hi, 

could it be here?
https://github.com/pehapkari/pehapkari.cz/blob/9293b6415c0c053e21c8c86374df0a043d57dbe9/packages/blog/src/Controller/PostController.php#L27
