### ISSUE TITLE
Malformed phpstan.neon obscuring issues

### ISSUE THREAD

**Issue by muglug** [pehapkari/pehapkari.cz#318]
I imagine this line is incorrect: https://github.com/pehapkari/pehapkari.cz/blob/a066effbc607b1d03dbbd1904bb6685dc8d22c4d/phpstan.neon#L31

When it's shortened there are 31 new errors found.

**Comment by muglug** [comment]
The bug is a missing `\` before `|null` at the end – it removes all nullable issues erroneously

**Comment by ondrejmirtes** [comment]
PHPStan shows this as a warning for the past few months since 0.12.8 https://github.com/phpstan/phpstan/releases/tag/0.12.8

**Comment by ondrejmirtes** [comment]
Why it doesn't show up in the build here is because of the custom error formatter I guess.
