### ISSUE TITLE
Deprecatin notice under article

### ISSUE THREAD

**Issue by racinmat** [pehapkari/pehapkari.cz#330]
Hi, there is deprecation notice under the article https://pehapkari.cz/blog/2017/03/13/how-to-add-https-to-github-pages-in-6-steps/.

![image](https://user-images.githubusercontent.com/5525771/31906340-1fd9918e-b831-11e7-9a6f-f3f8aa64e3fd.png)

**Comment by TomasVotruba** [comment]
Thanks for reporting, resolved by https://github.com/pehapkari/pehapkari.cz/commit/d88336c58003229a95e5b8d9e5a29550cb48fe84

Feel free to send PR next time, if you find time.
