### ISSUE TITLE
Unable to run project locally using docker-compose command

### ISSUE THREAD

**Issue by Lexinek** [pehapkari/pehapkari.cz#353]
Hi, i followed guide at https://github.com/pehapkari/pehapkari.cz/blob/master/README.md step by step as well tried to run app using docker (https://github.com/pehapkari/pehapkari.cz/blob/master/docs/docker.md) but unsuccessfully.

When accessing `http://localhost:8000` i see 404 error: 
<img width="1680" alt="screenshot 2017-12-06 15 09 41" src="https://user-images.githubusercontent.com/3995003/33665532-891aa718-da97-11e7-81ca-0d85b86eb97c.png">

`docker-composer up app` is not working at all:
<img width="1057" alt="screenshot 2017-12-06 15 10 48" src="https://user-images.githubusercontent.com/3995003/33665617-d80e6cd8-da97-11e7-944a-d18bfca68389.png">

Tried on master.

Any tips how to make it work locally? I need to test the code before i send PRs :-)

**Comment by Lexinek** [comment]
Ok, seems that i have found the problem, statie was generating sources for over 5 minutes with alot of warnings and deprecated messages - it was confusing for me that i have to wait while statie generates the code. 

So only the docker is not working.

**Comment by TomasVotruba** [comment]
@newPOPE Hi, could you look on this?

**Comment by newPOPE** [comment]
Hi, I check it. @Lexinek can you try this version https://github.com/newPOPE/pehapkari.cz? What OS you have? (Linux or OSX, if OSX how you run Docker? Docker for MAC or Parallels, Dropbox?).

**Comment by TomasVotruba** [comment]
@Lexinek Is this still an issue?

**Comment by Lexinek** [comment]
@newPOPE Im sorry, absolutely forgot about this issue.

I am running on OSX and using the Docker for MAC.

Works fine with the new image 😉 there were few warnings but completed successfully. Thank you

Anyways i have an advice, you could add `RUN composer global require hirak/prestissimo --no-interaction --ansi` to your dockerfile as it will fasten up installing composer dependencies drastically!

**Comment by Lexinek** [comment]
@newPOPE sorry, in the end, npm errors ocurred:

```
app_1  | npm ERR! path /src/node_modules/write-good/bin/write-good.js
app_1  | npm ERR! code ENOENT
app_1  | npm ERR! errno -2
app_1  | npm ERR! syscall chmod
app_1  | npm ERR! enoent ENOENT: no such file or directory, chmod '/src/node_modules/write-good/bin/write-good.js'
app_1  | npm ERR! enoent This is related to npm not being able to find a file.
app_1  | npm ERR! enoent 
app_1  | 
app_1  | npm ERR! A complete log of this run can be found in:
app_1  | npm ERR!     /root/.npm/_logs/2018-03-08T11_33_18_244Z-debug.log
```

This looks like issue with `package.json`

**Comment by Lexinek** [comment]
If i run `npm install` on my host (not in docker), it finishes successfully

**Comment by newPOPE** [comment]
@Lexinek thanks, I will check it.

**Comment by newPOPE** [comment]
@Lexinek hi I check problem which you mention. This version is rebased to actual master https://github.com/newPOPE/pehapkari.cz and can build & run with no problem (OSX, parallels) so I think issue is for Docker for MAC. Maybe someone with native docker on Linux can verify master.

**Comment by TomasVotruba** [comment]
Closing as explained by @newPOPE as Docker + MAC issue

**Comment by Lexinek** [comment]
Many thanks to both of you! The rebased version was working as i mentioned, so i think everything is working, every is happy 😄 thanks once again!
