### ISSUE TITLE
Provide minimum database data required (fixtures)

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#36]
Hi!

Please provide a SQL file or let's implement fixtures. This error happens when installing the app with an empty database.

In the documentation, there is a `2. Database setup` info, but I don't know where to get that MySQL dump _-).

<img width="1082" alt="screenshot 2019-01-04 22 00 16" src="https://user-images.githubusercontent.com/3995003/50710735-241e7900-106c-11e9-82ab-4c23cd24be7d.png">

**Comment by TomasVotruba** [comment]
Hi, this should work without any data.

Just change the return value to `?Place` everywhere this happens to you. PR is the best

**Comment by JanMikes** [comment]
Okay, in that case, consider this as a bug report and I might fix it after I finish my work on docker and auto-deploy 😄 

Btw I consider nullable return `?Place` as smelly design, wouldn't it be cleaner to throw an exception? More strict typed code should prevent possible bugs when writing code, what do you think?

**Comment by TomasVotruba** [comment]
That's EasyAdmin requirement. Better done than perfect :)

Just fix these as you go and send PR in the end, when done.
