### ISSUE TITLE
Is it possible to add Postgres to travis?

### ISSUE THREAD

**Issue by simara-svatopluk** [pehapkari/pehapkari.cz#379]
Hi guys,

I'm writing an article about a Doctrine and I would love to have access to the database so I could run tests against it. The code is already done and tests are passing *on my machine*.

Could You please help me with adding the Postgres to the Travis?

**Comment by TomasVotruba** [comment]
Hey, do you need Doctrine to run on database or really Postgres?

Doctrine works well with sqlite on tests, which are fast and easy to run and setup. I've used for all my Doctrine packages I used on Postgres projects.

Here is all I used: [Kdyby\Doctrine for Nette](https://github.com/DeprecatedPackages/DoctrineFixtures/blob/a18ae07d3bd5c22537e0a06a93db0765d2b8b3c6/tests/config/default.neon#L14)

**Comment by simara-svatopluk** [comment]
The article will be also about system testing against a real database. So for readers, it would be nice to see these tests working. Test against postgres is a bit more difficult than testing against sqlite.

If it is not possible to have postgres tests, then sqlite will be good enough :-) The rest will be written in the article maybe with a link to my GitHub.

**Comment by simara-svatopluk** [comment]
I just started to work on the article, and first I'm summarizing what do I need. So I don't have a failing Travis yet

**Comment by enumag** [comment]
I also recommend using sqlite for the tests. If it is necessary it should be possible to add postgres using docker.

**Comment by simara-svatopluk** [comment]
It is not absolutely necessary, but it would be a benefit for readers.

Well, the Docker is not my friend, so I cannot do it myself. If You can help with adding the postgres into the Travis, it would be great, otherwise, tests will run against sqlite :-)

**Comment by TomasVotruba** [comment]
@simara-svatopluk  Also think about other people that will add post with tests to this repo. Docker as requirement to run simple website just to add 100 markdown lines would probably turn them down.

**Comment by simara-svatopluk** [comment]
good point, sqlite is enough
