### ISSUE TITLE
[lectures] add edit link on the bottom, as posts have

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#390]

**Comment by TomasVotruba** [comment]
This is actually about 2 issues:

- posts are missing footer - https://pehapkari.cz/blog/2018/02/28/domain-driven-design-repository, the black panel on the bottom, like on homepage
- and under lectures is the same, but **Oprav nám ji, prosím** link is missing

![image](https://user-images.githubusercontent.com/924196/37037028-b7581876-2151-11e8-87e5-2231983d56bd.png)

**Comment by EdoBarnas** [comment]
I will try to process that.

**Comment by TomasVotruba** [comment]
Fixed via #394
