### ISSUE TITLE
Stránky o školení mají všechny stejný titulek v prohlížeči

### ISSUE THREAD

**Issue by TomasPilar** [pehapkari/pehapkari.cz#417]
Všechny stránky o školení mají `<title>Děláš v PHP? Jsi jedním z nás</title>` z pohledu SEO a vyhledávačů je potřeba mít univerzální titulky pro každou stránku. Zde by tím titulkem mohl být název školení (stejně jako je na detailu článku titulkem jeho název).

**Comment by TomasVotruba** [comment]
Dobrý nápad :+1: 

Co ode mě potřebuješ, abys to dokázal přidat, stejně jako to mají posty?

**Comment by TomasPilar** [comment]
Heleď já asi nic, nevím přesně, jak to ve Statie funguje a jak to mají implementované  blogové příspěvky. Pouze jsem si toho všiml, když jsem opravoval typo ve svém školení. :-) 
Pokud se to hodí, tak nechám implementaci asi na někom zkušenějším.

**Comment by TomasVotruba** [comment]
Jestli znáš trochu Nette a Latte, tak tak ;) 

Koukám na to a je to tím, že školení mají `name` místo `title`, jinak by to už dávno bylo.
Sem by mělo jít stačit přidat: `$name` 

https://github.com/pehapkari/pehapkari.cz/blob/f531874fe2dd1626564dbd96df4d878ccd3efed5/source/_snippets/head.latte#L35

Nebo to líp sjednotit, obojí na "name", aby nedocházelo k těmto wtf:
