### ISSUE TITLE
Check Gitlab's webhook

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#42]
@TomasVotruba please be so nice and check webhooks.

I am not sure if I did not break anything by moving around and renaming project/organization on Gitlab.

The project id is `10224407`

I open this because I just pushed and it did not trigger the build on Gitlab - please check if there is 200 response and the webhook is active.

Thank you very much (this is only a panic alert and maybe there is nothing wrong 😄 )!

**Comment by JanMikes** [comment]
Seems to be working again, a mystery 🎁

**Comment by TomasVotruba** [comment]
I didn't do anything :smile:
