### ISSUE TITLE
404 for prism.js

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#43]
<img width="1674" alt="screenshot 2019-01-09 03 42 32" src="https://user-images.githubusercontent.com/3995003/50873566-d33ab780-13c0-11e9-9fb9-cc2fe9bcc833.png">

In PHP logs:
```
WARNING: [pool www] child 29 said into stderr: "2019-01-09T02:41:50+00:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /assets/prism/prism.js" (from "https://phpskoleni.cz/")" at /app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 139"
```

Caused by `<script src="/assets/prism/prism.js"></script>` in `footer.html.twig` can we remove this line? Or shall we put prism into assets? 😉

**Comment by TomasVotruba** [comment]
> Or shall we put prism into assets? 

:+1:
