### ISSUE TITLE
Prepare PHP Prague 2018 site

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#440]
- [x] redirect https://phpprague.cz → https://pehapkari.cz/php-prague/
- [x] add basic info
- [x] prepare space for partners
- [x] refresh logo - could you update the logo @chemix - DONE
- [x] ask people abroad for talks
    - [x] PL
    - [x] Dresden
    - [ ] Berlin
    - [ ] Munich
    - [x] Austria

Add more tasks, if I missed smth

**Comment by chemix** [comment]
![website](https://user-images.githubusercontent.com/42802/38901962-a0cddf82-429e-11e8-8d42-913adab432f4.png)

or svg version 

http://jsfiddle.net/yxmwgoun/1/embedded/result/

**Comment by TomasVotruba** [comment]
Thanks for fast work

Could you add English date "June 23, 2018" so people abroad understand?

**Comment by chemix** [comment]
![website](https://user-images.githubusercontent.com/42802/38920092-bf17ffbe-42f2-11e8-9dbc-9c4b005ea3f3.png)

http://jsfiddle.net/chemix/yxmwgoun/2/embedded/result/

**Comment by TomasVotruba** [comment]
Tthe best, thanks :+1:

**Comment by TomasVotruba** [comment]
Could you link the playlist? Is it complete = including me? :)

**Comment by chemix** [comment]
Check if playlist exists, or create new one. 

all videos are online

![image](https://user-images.githubusercontent.com/42802/45945517-09108780-bfee-11e8-8b19-7417801326e8.png)

**Comment by TomasVotruba** [comment]
Where?

**Comment by chemix** [comment]
https://www.youtube.com/channel/UCTBgI1P8xIn2pp2BBHbv5mg/videos?shelf_id=1&view=0&sort=dd there are all videos uploaded to youtube channel pehapkari

**Comment by TomasVotruba** [comment]
Done in: https://github.com/pehapkari/pehapkari.cz/commit/b6edb3f41fdf0e394149c3b58f20dd62a2706704

https://pehapkari.cz/php-prague

**Comment by chemix** [comment]
❤️

**Comment by TomasVotruba** [comment]
I also postd on socials:

- https://twitter.com/Pehapkari/status/1046778642565492737
- https://www.facebook.com/pehapkari/photos/a.966414480075029/1867209809995487/?type=3&theater
