### ISSUE TITLE
Chybný odkaz z twitch.tv na Slack pozvánku

### ISSUE THREAD

**Issue by Qitek85** [pehapkari/pehapkari.cz#489]
1. chci se nechat pozvat na Slack Péhápkařů
2. jsem na www.twitch.tv/pehapkari
3. odkaz z textu: "Nech si poslat pozvánku na mail" vede na: https://slackinvite.me/to/pehapkari
4. na tomto odkazu je reklama na elektronické cigarety

**Comment by TomasVotruba** [comment]
Ahoj Vítku,

díky za report.

Správný odkaz je: https://pehapkari.herokuapp.com/

@jakubkratina Můžeš to fixnout prosím?

**Comment by TomasVotruba** [comment]
Ping @jakubkratina

**Comment by jakubkratina** [comment]
Will do!

**Comment by jakubkratina** [comment]
Opraveno, díky.

**Comment by TomasVotruba** [comment]
Díky Kubi <3
