### ISSUE TITLE
SocialTags block issue

### ISSUE THREAD

**Issue by xpavp03** [pehapkari/pehapkari.cz#522]
When you look into the source code of
https://pehapkari.cz/blog/2017/03/27/multiple-php-versions-the-easy-way/

you'll find these tags at the very end, after /BODY. They're supposed to go into HEAD:
meta property="og:type" ...

**Comment by TomasVotruba** [comment]
Please use English

**Comment by xpavp03** [comment]
When you look into the source code of
https://pehapkari.cz/blog/2017/03/27/multiple-php-versions-the-easy-way/

you'll find these tags at the very end, after /BODY. They're supposed to go into HEAD:
meta property="og:type" ...

**Comment by TomasVotruba** [comment]
Thanks, I'll check it
