### ISSUE TITLE
Strip special html entities from title

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#537]
There is issue when title contains html entities like `&nbsp;` it is displayed in the `<title>` as well:  
<img width="294" alt="screenshot 2018-11-12 17 15 34" src="https://user-images.githubusercontent.com/3995003/48360043-942d0600-e69e-11e8-9cc9-3a17ef85f106.png">

**Comment by TomasVotruba** [comment]
Dare your fix that in Symfony code? :)
