### ISSUE TITLE
Add contact

### ISSUE THREAD

**Issue by martinahynkova** [pehapkari/pehapkari.cz#550]
![kontakt](https://user-images.githubusercontent.com/24881512/50289644-bb2ee280-0469-11e9-83a7-0130bc4a7f4a.png)

**Comment by martinahynkova** [comment]
Něco takového, můžeš upravit nebo zkrátit cokoliv...
chtěla jsem dát na konec, ale na téhle stránce je konec v nedohlednu, je tam strašně moc věcí.

**Comment by TomasVotruba** [comment]
Ok, přidáno na nový web
