### ISSUE TITLE
Missing / in url causes 500

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#60]
@TomasVotruba maybe bug in router?

https://pehapkari.cz/blog/2019/04/20/how-we-migrated-54-357-lines-of-code-nette-to-symfony-in-2-people-under-80-hours

vs 

https://pehapkari.cz/blog/2019/04/20/how-we-migrated-54-357-lines-of-code-nette-to-symfony-in-2-people-under-80-hours/

**Comment by TomasVotruba** [comment]
Thanks for reporting!
