### ISSUE TITLE
Connection to slack community

### ISSUE THREAD

**Issue by DaweTaller** [pehapkari/pehapkari.cz#61]
Channel for programming tips, jobs, meetings, jokes, etc... Channel is public :)

Url: lbc-devs.slack.com

**Comment by TomasVotruba** [comment]
It would be great to have one place to operate from. *United we stand* :)

Just having "mesto-<slug>" channels to keep it local, and #symfony, #nettefw, #laravel, #codeception... etc. for technology topics. We already did that with "Symfonisti" and "Nette camp".

What do you think?

https://twitter.com/Pehapkari/status/793120997276839940

**Comment by TomasVotruba** [comment]
Closing as slack is main way and there is info about this in #liberec channel.
