### ISSUE TITLE
[post ideas]

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#63]
Feel free to taky any topic. Just write in a comment you do so noone will take it too.

- [x] **what are tested articles and why** - ref https://twitter.com/hrachcz/status/816940948114571264 + make "Tester article" clickable to that article - #160
- [ ] bad practise: named services in Symfony
- [ ] drop getDoctrine() and custom repository in Symfony
- [ ] things you can do better in Symfony right from the start
- [x] composer-patches - https://github.com/cweagans/composer-patches

**Comment by TomasVotruba** [comment]
Ping @enumag , would you take this topic?

**Comment by enumag** [comment]
@TomasVotruba Hmm... is there even a way to not name services? (Of course the primary concern is to not use the names outside of yaml.)

**Comment by TomasVotruba** [comment]
@enumag There [might be](https://github.com/symfonette), but that's not the goal here. Step-by-step decoupling might to lead that in time.

**Comment by TomasPilar** [comment]
@TomasVotruba Post about "composer-patches" is here https://github.com/pehapkari/pehapkari.cz/pull/174 :)

**Comment by TomasVotruba** [comment]
Not relevant anymore. Feel free to inspirace, in case you're looking for some posts
