### ISSUE TITLE
ShouldNotHappenException + weird blog posts routing

### ISSUE THREAD

**Issue by JanMikes** [pehapkari/pehapkari.cz#85]
These links will get routed to same article, how? Shouldn't the url be unique?

- https://pehapkari.cz/blog/2018/03
- https://pehapkari.cz/blog/2018/03/28/
- https://pehapkari.cz/blog/2018/03/28/domain-driven-design
- https://pehapkari.cz/blog/2018/03/28/domain-driven-design-services-factories

Other thing is this url https://pehapkari.cz/blog/2018/03/28/domain-driven-design-services-factories%27 causes `ShouldNotHappenException`:

`/src/Controller/BlogController.php in Pehapkari\Controller\BlogController::post at line 54`

Should it throw HttpNotFound exception instead?

**Comment by TomasVotruba** [comment]
Agreed :+1:

**Comment by JanMikes** [comment]
I think it is not fixed yet 😄  try https://pehapkari.cz/blog/favicon.ico 

<img width="638" alt="Screenshot 2019-06-07 10 08 57" src="https://user-images.githubusercontent.com/3995003/59090178-5a5a7000-890c-11e9-83e8-f58a3ef8ad49.png">

**Comment by TomasVotruba** [comment]
Could you add correct exception?
