### ISSUE TITLE
Add "Press" link with Logo and visuals for branding

### ISSUE THREAD

**Issue by tomasfejfar** [pehapkari/pehapkari.cz#93]
I wanted to use pehapkari logo with text for my presentation, but I had to download it from Facebook :( It could be as simple as a link to ZIP file with logo files. Could be useful for partners as well - when they want to blog about an event the supported for example.

**Comment by TomasVotruba** [comment]
After new one is picked (https://www.facebook.com/pehapkari/posts/1136780413038434), we can make some "for media" section.

Will you prepare this section then?

**Comment by tomasfejfar** [comment]
Oh, I thought that the amazing elephant is winner hands down :D

![image](https://cloud.githubusercontent.com/assets/642928/20232892/d6a19294-a86b-11e6-9b41-20b439d5053f.png)

**Comment by tomasfejfar** [comment]
I don't think we need "section" per-se. Jist a link in footer to zip file is good enough (KISS)

**Comment by TomasVotruba** [comment]
@tomasfejfar Could you connect with @chemix to get the logo and prepare this zip?

**Comment by tomasfejfar** [comment]
Could do. But actually @chemix will need to do most of the work anyway (he'll need to create the zip to send me anyway). 

@chemix: If you want me to do it anyway, let me know and I'll prepare a PR (or ideally start a branch here with the zip and I'll add it to the page and create PR from it).

**Comment by TomasVotruba** [comment]
Resolved by #124
