### ISSUE TITLE
Vocabulary: Contributing issues

### ISSUE THREAD

**Issue by hranicka** [pehapkari/pehapkari.cz#97]
Won't it be complicated to update vocabulary via pull requests?
Merge conflicts, duplicated terms, terms not merged but waiting in pull requests, etc.?

I know why it's done this way now. Simplicity. Just edit a template. Other solutions are expensive (time).

But when more people contribute to vocabulary, it should be better if someone (i.e. me) creates a web interface for adding these terms. They can be sorted automatically A-Z, no one cares about it.

Added ones shouldn't be visible in vocabulary by default. But should be visibled for someone who needs contribute and wants to see not confirmed ones. People should have an option to add and edit.

Admin should have an option to edit, delete and confirm user changes (they'll be visible publicly then).

---

Is this solution draft too complicated and contributing by pull request will be enough?

**Comment by TomasVotruba** [comment]
Thanks for bringing that up.

The main goal is sustainability, so creating some other PHP/Mysql application would be great and handy, yet unusable in year or 2, hard to scale and closed-source.

> They can be sorted automatically A-Z, no one cares about it.

With Statie (static site generator), you can do that. It's matter of another PR.

This page was created yesterday, so it's not final version and your suggestions are valid and shall be implemented.

Doing this in closed source, it would be probably still in progress for weeks.

If I didn't answer you exactly to your needs, what do you suggest?

---

If you need to learn more about Statie or it's abilities, I'm happy to help.

**Comment by mrtnzlml** [comment]
@hranicka At this moment it's good enough and it's up to maintainers to merge those changes as soon as possible. The main point is to do minimal but even though valuable vocabulary (as a first draft).

**Comment by TomasVotruba** [comment]
@mrtnzlml Could you merge them please as your created and have some idea how to do it? I've added you to maintainers.

**Comment by hranicka** [comment]
I know, it's the best (simplest) solution now. And will be ok until there will ve only a few opened merge requests. And probably... there won't be a lot of really concurrent contributions. Maybe at the beginning but not later when there will be nearly all common used terms.

Current simple solution is good when pull requests won't be opened weeks or months :)

Thank you @TomasVotruba, I'll look at Statie. 

Thanks @mrtnzlml for this minimalistic and simple solution. It's enough most the time for given purposes, you're right. 

Closing the issue?

**Comment by TomasVotruba** [comment]
>  And probably... there won't be a lot of really concurrent contributions.

Actually, I think this solve new feature on Github: https://github.com/blog/2243-rebase-and-merge-pull-requests

AFAIK, conflicts should not happen, if different parts of pages are edited. But not I haven't tested that.

> Current simple solution is good when pull requests won't be opened weeks or months :)

That shall not happen till I'm alive :D 

> They can be sorted automatically A-Z, no one cares about it.

We could implement this, if there will be enough natural fails. Meaning if there will be significant number of alphabetical miss-placement, it will be automated.

**Comment by TomasVotruba** [comment]
@mrtnzlml Thanks!
