### ISSUE TITLE
Vocabulary: terms ideas from first core-meetup

### ISSUE THREAD

**Issue by mrtnzlml** [pehapkari/pehapkari.cz#98]
There are few word ideas as an output from the first core-meetup. It would be great to explain what's going on there. It's good starting point if you don't have good ideas... :)

- [ ] service
- [ ] AMQP (RabbitMQ)

Ideas from @tomaskazatel:
- [ ] Semantics

Ideas from @kbarborak:
- [x] unit test
- [x] deployment
- [x] continuous integration
- [x] PSR
- [x] VCS or (maybe and?) Git

**Comment by tomaskazatel** [comment]
My ideas words for vocabulary

- [ ] Webhosting
- [ ] Cookies
- [ ] Regular expressions
- [ ] MVC
- [ ] Data type
- [ ] Variables
- [ ] Algorithm
- [ ] Object
- [ ] Class
- [ ] Instance
- [ ] Semantics
- [ ] Singleton
- [ ] Interface
- [ ] UI = user interface
- [ ] UX = user experience
- [ ] Constructor
- [ ] Agile
- [ ] Refactoring

These terms are less general but for dictionary perfect fit 😄

**Comment by kbarborak** [comment]
My two cents for another contributors:

- unit test
- deployment
- continuous integration
- PSR
- VCS or git

**Comment by TomasVotruba** [comment]
I've cleared up completed ones (~80 % of all), so it's easier to read. Feel free to add new ones.

**Comment by castamir** [comment]
API
Rest (API)
Constructor hell
Continuous Delivery
End-2-End tests
+ Factory (i don't like current description, it should be more about responsibility for creating object and SRP)
IDE
Integration Tests
Lazy loading
Test Driven Development
many many tools that that everyone should at least know about (Gihub, Gitlab, Travis, Selenium, all bunch of client side tools)
many many other patters like MVVM, Abstract class abstract factory, Facade (my favorite one), Prototype, Adapter, Observer (Publish-subscribe), Chain of Responsibility, Strategy etc..
many many terms from development process (analysis, design, development, testing) and its tools like UML

There is so many terms to describe, so many areas to cover...

**Comment by mrtnzlml** [comment]
@castamir Feel free to send PR if you want. Otherwise your comment will die in eternity.
